### ISSUE TITLE
Search Feature is not working properly

### ISSUE THREAD

**Issue by rahul286** [desaiuditd/TweetUdit#1]
2 issues:
1. It search by twitter handle alone. It will be good if I can search by name. If its not possible, just anser why in this thread.
2. After searching, when I see results, I do not get "Download PDF" button.

**Comment by desaiuditd** [comment]
1. Search only by twitter handle : In the assignment it was not mentioned anything, hence i put it by twitter handle straight forward, but i can enhance that search mechanism. I'll get back to you asap on that once i update it.
2. Download PDF : Again I misinterpreted it to be only related to the user who logged in and resulting in putting the download button to tweets only to the user and not to that of his/her follower. I'll add that too.

**Comment by rahul286** [comment]
Thanks.

For PDF, just open it once and check formatting. I noticed an empty page towards end.

**Comment by desaiuditd** [comment]
Yeah, I too had noticed it. Actually I was facing issues in setting all the content right in printable PDF format. I guess I'll have to play a bit with the margins of the content.

**Comment by rahul286** [comment]
Yep. Getting PDF formatting is tough job! ;-)

PDF is friendly on "reader" side only. Creating rich-media PDF programatically will take some extra time & efforts.

**Comment by desaiuditd** [comment]
1. Search function optimized : search by twitter handle as well as name is added
2. Download PDF on Follower's Timeline is added.
3. PDF printable view is enhanced as well. (Unnecessary margin removed.)
