### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by rahul286** [desaiuditd/TweetUdit#2]
Please improve UI...

![TweetUdit Rahul Bansal](https://f.cloud.github.com/assets/4115/254682/22f3d8a2-8bf9-11e2-865c-f1104d5cb3dd.jpg)

**Comment by desaiuditd** [comment]
Regarding the color scheme; I've directly picked up the themes from the user's twitter profile. The idea was to give the customized home page to each and every user. So when the user logs in he gets the look and feel the same as the one on his own twitter page.
So one solution can be i can re-design it to be a common UI page for all the users and the idea of customization can be removed.

**Comment by rahul286** [comment]
I noticed your efforts to pull users background and home env. :+1:  for that :-)

I have no issues with background, but it seems there is some transparency or gradient property making contrast poor on top part. Please check foreground/background contrast on top-right side and bottom-right side. You will background behind first user is darker and last user in list in lighter.

**Comment by desaiuditd** [comment]
Yeah, I understood it. Probably, I had tested it only from my Twitter account and there it was making all sense; so I did not think much on it. I'll try out with few more themes and make check it out.

**Comment by rahul286** [comment]
It may be the case.

I tried opening http://cadet.web44.net/TweetUdit 

It looks like a small CSS glitch.

**Comment by desaiuditd** [comment]
Yeah ... I looked into it.
The server on which I hosted the project is under D-DOS attack and hence the hosted sites are down. I'll try to host the project on another hosting server.
Is it fine if I update the web url over here or do I need to notify you about it ?

**Comment by rahul286** [comment]
Sure. Once we start reviewing applications we look for demo URL at https://github.com/desaiuditd/TweetUdit

Just edit it there!

By the way you can try http://www.heroku.com/ (They provide trial account for facebook-apps. Not sure if they do same for twitter-apps)

Other way will be to use Google Apps engine (It will be tricky to get PHP running there!)

**Comment by desaiuditd** [comment]
Sure.
Thanks.

**Comment by desaiuditd** [comment]
UI improved. Code updated + Changes reflected on the same hosting server as well.
