### ISSUE TITLE
Enhancement - Favorites management

### ISSUE THREAD

**Issue by rahul286** [desaiuditd/TweetUdit#3]
On twitter, a user can favorite tweets (its like bookmarking tweet on twitter itself)
1. Create a new screen called "manage favorite".
2. Assuming visitor is authenticated, fetch users own favorite. Show them on a single-page. Show them in tabular format. Place a checkbox next to each tweet. Place a check-all/uncheck-all box in table-header row.
3. User can check/uncheck favorite tweets...
4. A big "unfavorite" button to unfavorite select tweets should be on top and bottom of table.
#### Test Case
1. Favorite some tweets from web-interace, external app.
2. Go to assignment >> "manage favorite" section
3. Favorite tweets should be displayed there.
4. Uncheck few/all tweets from list and click "unfavorite" button.
5. Goto step 2 above to verify if those tweet disappear from favorite list.
6. Crosscheck step 5 output from web-interface.

**Comment by desaiuditd** [comment]
I'll get back to you on this too once I'm done with this.

**Comment by rahul286** [comment]
Its fine. Take your time.

**Comment by desaiuditd** [comment]
In this module, do we have a assumption that there are already few tweets marked as favourite in the user's account ?
If no, then in case of no tweets marked as favourite the assignment app will display a blank page mentioning "no favourite tweets". And in that case the user would not be able to add any new tweets in the favourite section.
Is this what is expected ?

**Comment by rahul286** [comment]
Yes. 

For current assignment scope - a user is expected to make tweets favorite from twitter.com or other apps. 

We will only give option to "bulk unfavorite".

If no favorite tweets are present, it will be enough to show a message "no favourite tweets".

**Comment by desaiuditd** [comment]
Ok .. sure.
Got it.

**Comment by desaiuditd** [comment]
Functionality Added

**Comment by rahul286** [comment]
Timestamp are not correct - a small but irritating bug

**Comment by rahul286** [comment]
Are you working on it? It looks broken at the moment?

![TweetUdit Favorites-1](https://f.cloud.github.com/assets/4115/313295/bd583672-97a7-11e2-99ba-1fb0046d80a0.jpg)

**Comment by desaiuditd** [comment]
Hi,
it seems a server glitch .... I was not working on it. Sorry about that. I did not get chance to deploy it on either heroku or GAE.

I've resolved the timestamp bug. The day of the month was getting incorrect. Though the HH:mm:ss that I'm getting from Twitter API is itself not matching with the one from twitter.com. So I'm thinking on it. It maybe happening because of the different timezones of the server but I'm not sure.

**Comment by desaiuditd** [comment]
I got that figured out too. As I had thought, the problem was of the timezone only. The bug is fully resolved now.

**Comment by desaiuditd** [comment]
Currently I've set it to default Indian Timezone i.e., India/Kolkata (+5.30). I'm working on to set it according to the user from where he logs in. I can pick up the utc_offset from his/her profile and set the timezone accordingly.

**Comment by rahul286** [comment]
## Fine.

Rahul Bansal | Founder & CEO | rtCamp Solutions Pvt. Ltd.
Skype: rahul286 | Twitter: @rahul286 | Web: http://rtcamp.com/
